variables:                         &default-vars
  CI_IMAGE:                        "paritytech/ci-linux:production"
  # variables related to generating docs & versioning
  RUSTDOCS_DEPLOY_REFS:            "main v3.0.0+monthly-2021-08 v3.0.0+monthly-2021-09"
  INDEX_TPL:    ".maintain/docs-index-tpl.ejs"
  REPO_NAME:    "advent-of-code-2020"
  REPO_URL:     "https://${GITHUB_TOKEN}@github.com/jimmychu0807/${REPO_NAME}.git"
  DOC_INDEX_PAGE: "report_repair/index.html"
  LATEST_DEST: "main"

workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

before_script:

build_rustdocs:
  stage: deploy
  rules:
    - if: "[[ \" $RUSTDOCS_DEPLOY_REFS \" =~ \" ${CI_COMMIT_REF_NAME} \" ]]"
  image: ${CI_IMAGE}
  script: |
    mkdir public
    cargo doc --no-deps --workspace --all-features --verbose
    rm -f ./target/doc/.lock
    mkdir -p public/${CI_COMMIT_REF_NAME}
    cp -rf target/doc/* public/${CI_COMMIT_REF_NAME}
    echo "<meta http-equiv=refresh content=0;url=${DOC_INDEX_PAGE}>" > public/${CI_COMMIT_REF_NAME}/index.html
  artifacts:
    paths:
      - public

publish_rustdocs:
  stage: deploy
  needs:
    - job: build_rustdocs
      artifacts: true
  image: node:16
  script: |
    rm -rf /tmp/*
    mv -f public/${CI_COMMIT_REF_NAME} /tmp/docs

    # setup git lfs
    curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
    apt install git-lfs

    # generate index.html based on RUSTDOCS_DEPLOY_REFS
    yarn global add ejs
    ejs ${INDEX_TPL} -i "{\"deploy_refs\": \"${RUSTDOCS_DEPLOY_REFS}\", \"repo_name\": \"${REPO_NAME}\", \"latest\": \"${LATEST_DEST}\"}" > /tmp/index.html

    # Set git config
    rm -rf .git/config
    git config user.email "gitlab-ci@hkwtf.com"
    git config user.name "${GITHUB_USER}"
    git config remote.origin.url ${REPO_URL}

    # switch over to `gh-pages` branch
    git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
    git fetch origin gh-pages
    git checkout gh-pages

    # Remove directories no longer necessary, as specified in $RUSTDOCS_DEPLOY_REFS.
    # Check if $RUSTDOCS_DEPLOY_REFS is non-space
    if [[ ! -z ${RUSTDOCS_DEPLOY_REFS// } ]]; then
      for FILE in *; do
        if [[ ! " $RUSTDOCS_DEPLOY_REFS " =~ " $FILE " ]]; then
          echo "Removing ${FILE}..."
          rm -rf $FILE
        fi
      done
    fi

    # Move the index page & built back
    mv -f /tmp/index.html .
    # Ensure the destination dir is clear
    rm -rf ${CI_COMMIT_REF_NAME}
    mv -f /tmp/docs ${CI_COMMIT_REF_NAME}

    # Add the symlink
    ln -sf ${LATEST_DEST} latest

    # push it back to github gh-pages
    git add --all --force
    git commit -m "Updated docs for ${CI_COMMIT_REF_NAME}" || echo "___Nothing to commit___"
    git push origin gh-pages --force

  after_script:
    - rm -rf .git/
