variables:                         &default-vars
  CI_IMAGE:                        "paritytech/ci-linux:production"
  RUSTDOCS_DEPLOY_REFS:            "main v3.0.0+monthly-2021-08 v3.0.0+monthly-2021-09"
  DEFAULT_RUSTDOCS_VER:            "main"
  INDEX_TPL:                       ".maintain/docs-index-tpl.ejs"

workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

before_script:

build_rustdocs:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main" || $CI_COMMIT_REF_NAME == "v3.0.0+monthly-2021-08" || $CI_COMMIT_REF_NAME == "v3.0.0+monthly-2021-09"'
  image: ${CI_IMAGE}
  script: |
    mkdir public
    cargo doc --no-deps --workspace --all-features --verbose
    rm -f ./target/doc/.lock
    mkdir -p public/${CI_COMMIT_REF_NAME}
    cp -rf target/doc/* public/${CI_COMMIT_REF_NAME}
    echo "<meta http-equiv=refresh content=0;url=report_repair/index.html>" > public/${CI_COMMIT_REF_NAME}/index.html
  artifacts:
    paths:
      - public

publish_rustdocs:
  stage: deploy
  needs:
    - job: build_rustdocs
      artifacts: true
  image: node:16
  script: |
    rm -rf /tmp/*
    mv -f public/${CI_COMMIT_REF_NAME} /tmp/docs

    # generate index.html based on RUSTDOCS_DEPLOY_REFS
    yarn global add ejs
    ejs ${INDEX_TPL} -i '{"deploy_refs" : "${RUSTDOCS_DEPLOY_REFS}"}' > /tmp/index.html

    # Set git config
    rm -rf .git/config
    git config user.email "gitlab-ci@hkwtf.com"
    git config user.name "${GITHUB_USER}"
    git config remote.origin.url "https://${GITHUB_TOKEN}@github.com/jimmychu0807/advent-of-code-2020.git"

    # switch over to `gh-pages` branch
    git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
    git fetch origin gh-pages
    git checkout gh-pages

    # Remove unnecessary stuff
    rm -rf *

    # Move the index page & built back
    mv -f /tmp/index.html .
    mv -f /tmp/docs ${CI_COMMIT_REF_NAME}

    # push it back to github gh-pages
    git add --all --force
    git commit -m "Updated docs for ${CI_COMMIT_REF_NAME}" || echo "___Nothing to commit___"
    git push origin gh-pages --force

  after_script:
    - rm -rf .git/
