variables:                         &default-vars
  CI_IMAGE:                        "paritytech/ci-linux:production"
  # variables related to generating docs & versioning
  RUSTDOCS_DEPLOY_REFS:            "main v3.0.0+monthly-2021-08 v3.0.0+monthly-2021-09"
  INDEX_TPL:    ".maintain/docs-index-tpl.ejs"
  REPO_NAME:    "advent-of-code-2020"
  REPO_URL:     "https://${GITHUB_TOKEN}@github.com/jimmychu0807/${REPO_NAME}.git"
  DOC_INDEX_PAGE: "report_repair/index.html"
  LATEST_DEST: "main"

workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

.install-git-lfs-script:      &install-git-lfs-script
  # setup git lfs
  - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
  - apt install git-lfs

.gen-index-script:            &gen-index-script
  # generate index.html based on RUSTDOCS_DEPLOY_REFS
  - yarn global add ejs
  - 'ejs ${INDEX_TPL} -i "{\"deploy_refs\": \"${RUSTDOCS_DEPLOY_REFS}\", \"repo_name\": \"${REPO_NAME}\", \"latest\": \"${LATEST_DEST}\"}" > /tmp/index.html'

.reset-gh-info-script:        &reset-gh-info-script
  # Set git config
  - rm -rf .git/config
  - git config user.email "gitlab-ci@hkwtf.com"
  - git config user.name "${GITHUB_USER}"
  - git config remote.origin.url ${REPO_URL}
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"

build_rustdocs:
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
    - if: $CI_COMMIT_REF_NAME =~ /^monthly-20[0-9]{2}-[0-9]{2}.*$/  # to support: monthly-2021-09+1
  image: ${CI_IMAGE}
  script:
    - mkdir public
    - cargo doc --no-deps --workspace --all-features --verbose
    - rm -f ./target/doc/.lock
    - mv target/doc public/${CI_COMMIT_REF_NAME}
    - echo "<meta http-equiv=refresh content=0;url=${DOC_INDEX_PAGE}>" > public/${CI_COMMIT_REF_NAME}/index.html
  artifacts:
    paths:
      - public

publish_rustdocs:
  stage: deploy
  needs:
    - job: build_rustdocs
      artifacts: true
  image: node:16
  before_script:
    - *install-git-lfs-script
  script:
    - rm -rf /tmp/*
    - mv -f public/${CI_COMMIT_REF_NAME} /tmp/docs

    - *gen-index-script
    - *reset-gh-info-script

    - git fetch origin gh-pages
    - git checkout gh-pages

    # Remove directories no longer necessary, as specified in $RUSTDOCS_DEPLOY_REFS.
    # Check if $RUSTDOCS_DEPLOY_REFS is non-space also.
    # Even though this block spans multiple lines, they are concatenated and run as a single line command, so note for the semi-colons.
    - if [[ ! -z ${RUSTDOCS_DEPLOY_REFS// } ]]; then
        for FILE in *; do
          if [[ ! " $RUSTDOCS_DEPLOY_REFS " =~ " $FILE " ]]; then
            echo "Removing ${FILE}...";
            rm -rf $FILE;
          fi
        done
      fi

    # Move the index page & built back
    - mv -f /tmp/index.html .
    # Ensure the destination dir is clear
    - rm -rf ${CI_COMMIT_REF_NAME}
    - mv -f /tmp/docs ${CI_COMMIT_REF_NAME}

    # Add the symlink
    - ln -sf ${LATEST_DEST} latest

    # push it back to github gh-pages
    - git add --all --force
    - git commit -m "Updated docs for ${CI_COMMIT_REF_NAME}" ||
      echo "___Nothing to commit___"
    - git push origin gh-pages --force
  after_script:
    - rm -rf .git/

republish_rustdocs:
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
  image: ${CI_IMAGE}
  before_script:
    - *install-git-lfs-script
  script:
    - *reset-gh-info-script
    - mkdir public
    - DEPLOY_ARR=($RUSTDOCS_DEPLOY_REFS)
    - git fetch origin
    - for REF in "${DEPLOY_ARR[@]}"; do
        git checkout $REF || (echo "${REF} not existed in remote." && continue);
        cargo doc --no-deps --workspace --all-features --verbose;
        rm -f ./target/doc/.lock;
        mv target/doc public/${REF};
        echo "<meta http-equiv=refresh content=0;url=${DOC_INDEX_PAGE}>" > public/${REF}/index.html;
      done
  artifacts:
    paths:
      - public
