[workspace]
members = [
	"shared",
	"01-report-repair",
	"02-password-philosophy",
	"03-toboggan-trajectory",
	"04-passport-processing",
	"05-binary-boarding",
	"06-custom-customs",
	"07-handy-haversacks",
	"08-handheld-halting"
]
